name: Build and Deploy Jekyll
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.3'
      - run: |
          bundle install
          bundle exec jekyll build
